### PR TITLE
DTSPO-6480 - enable Oauth on pip

### PR DESCRIPTION
**Pull request by endakelly**
JIRA link (if applicable)
https://tools.hmcts.net/browse/DTSPO-6480

Change description
Set ingress class for pip in demo to traefik and set enableOauth flag

Does this PR introduce a breaking change? (check one with "x")

[ ] Yes
[x] No

### CODE REVIEW

**Review by timja — COMMENTED** [review]
have they updated their charts to get the enableOauth flag?

**Comment by chris-pateman** [comment]
What version charts do we need and I can check?

**Comment by timja** [comment]
node.js - https://github.com/hmcts/chart-nodejs/releases/tag/2.4.2

I don't think Java is released yet @endakelly ?

**Comment by endakelly** [comment]
> hmcts/chart-nodejs@`2.4.2` (release)

I was under the impression from looking at chart-java that no changes were needed because disableTraefikTls is set in the pip java apps in sds-flux-config but that flag doesn't exist in chart-java

**Review by timja — APPROVED** [review]

**Comment by endakelly** [comment]
The following PRs are awaiting review that will update the pip charts. 
https://github.com/hmcts/pip-account-management/pull/27
https://github.com/hmcts/pip-channel-management/pull/12
https://github.com/hmcts/pip-data-management/pull/66
https://github.com/hmcts/pip-publication-services/pull/51
https://github.com/hmcts/pip-subscription-management/pull/38

Requested a review from @chris-pateman whenever you have time.

**Comment by chris-pateman** [comment]
Sorry just noticed this open.
@ChrisS1512  would you be able to update the Helm Chart versions please?

**Pull request closed without merging**
